package consted

const Deployment = "deployment"
const Pod = "pod"
const Service = "service"
const Statefulset = "statefulset"
const Daemonset = "daemonset"
const ConfigMap = "configmap"
const Ingress = "ingress"
const Secret = "secret"
const Tenant = "tenant"
const Project = "project"
const User = "user"
const Role = "role"
const RoleBinding = "rolebinding"
const ServiceAccount = "serviceaccount"
const Node = "node"
const Namespace = "namespace"
const Job = "job"
const CronJob = "cronjob"
const Pvc = "pvc"
const Pv = "pv"
const StorageClass = "storageclass"
